import type { useTranslations } from "next-intl";
import type { CSSProperties, ComponentProps, Dispatch, FormEvent, RefObject, SetStateAction } from "react";
import type { AuthUser, FeedPost, PostImageArchiveJob, ProtectedPackageJob, ReportReason } from "@/lib/types";
import type { ImageCarousel } from "./actions-panel";
import type { CommentDraftState, CommentState, DetailComment } from "./post-detail-types";

export type PostDetailSectionContentProps = {
  actionsOpen: boolean;
  attachment: FeedPost["attachment"] | null;
  author: string;
  authorHref: string;
  commentCount: number;
  commentFooterStyle: CSSProperties | undefined;
  commentInputExpanded: boolean;
  commentInputRef: RefObject<HTMLTextAreaElement | null>;
  commentPlaceholder: string;
  commentState: CommentState;
  commentText: string;
  comments: DetailComment[];
  cover: string | null | undefined;
  currentUser: AuthUser | null;
  detailDate: string;
  emblaApi: ComponentProps<typeof ImageCarousel>["emblaApi"];
  emblaRef: ComponentProps<typeof ImageCarousel>["emblaRef"];
  expandedCommentInputHeight: string;
  followButtonDisabled: boolean;
  followButtonLabel: string;
  handleCancelCommentInput: () => void;
  handleCopyPostLink: () => Promise<void>;
  handleDeleteComment: (comment: DetailComment) => Promise<void>;
  handleDeletePost: () => Promise<void>;
  handleDislikeToggle: () => Promise<void>;
  handleEditPost: () => void;
  handleFollowToggle: () => Promise<void>;
  handleLoadCommentReplies: (comment: DetailComment) => Promise<void>;
  handleNavigateAway: () => void;
  handleOpenCommentInput: (comment?: DetailComment, options?: { immediateFocus?: boolean }) => void;
  handleCreateProtectedPackage: () => Promise<void>;
  handleDownloadImageArchive: () => Promise<void>;
  handleDownloadProtectedPackage: () => Promise<void>;
  handlePurchaseContent: () => Promise<boolean>;
  handleRefreshImageArchive: () => Promise<void>;
  handleSaveCurrentImage: () => Promise<void>;
  handleSharePost: () => void;
  handleRetryComment: (comment: DetailComment) => Promise<void>;
  handleSubmitComment: (event: FormEvent<HTMLFormElement>) => Promise<void>;
  handleSubmitReport: (event: FormEvent<HTMLFormElement>) => Promise<void>;
  handleToggleCommentLike: (comment: DetailComment) => Promise<void>;
  highlightedCommentId: string | null;
  imageKey: string;
  imageViewerIndex: number | null;
  images: string[];
  slideshowImages: string[];
  isDeletingPost: boolean;
  isFollowingAuthor: boolean;
  isLoadingComments: boolean;
  isMutatingDislike: boolean;
  isPostDisliked: boolean;
  isPostOwner: boolean;
  isPostReported: boolean;
  isCreatingProtectedPackage: boolean;
  isDownloadingImageArchive: boolean;
  isDownloadingProtectedPackage: boolean;
  isPurchasingContent: boolean;
  isRefreshingImageArchive: boolean;
  isSubmittingComment: boolean;
  isSubmittingReport: boolean;
  locale: string;
  loginUnlockOpen: boolean;
  mode: "drawer" | "page" | "modal";
  mutatingCommentDeleteIds: Set<string>;
  mutatingCommentLikeIds: Set<string>;
  onCollect?: (post: FeedPost) => void;
  onLike?: (post: FeedPost) => void;
  onOpenChange: (open: boolean) => void;
  playableVideo: string | null;
  post: FeedPost;
  imageArchiveJob: PostImageArchiveJob | null;
  protectedPackageJob: ProtectedPackageJob | null;
  rawDetailContent: string | null;
  replyTarget: CommentDraftState["replyTarget"];
  reportDescription: string;
  reportReason: ReportReason;
  safeImageIndex: number;
  setActionsOpen: Dispatch<SetStateAction<boolean>>;
  setCommentDraft: Dispatch<SetStateAction<CommentDraftState>>;
  setImageViewerState: Dispatch<SetStateAction<{ index: number; postId: FeedPost["id"] } | null>>;
  setIsCommentInputFocused: Dispatch<SetStateAction<boolean>>;
  setLoginUnlockOpen: Dispatch<SetStateAction<boolean>>;
  setReportDescription: Dispatch<SetStateAction<string>>;
  setReportReason: Dispatch<SetStateAction<ReportReason>>;
  setShareOpen: Dispatch<SetStateAction<boolean>>;
  shareOpen: boolean;
  t: ReturnType<typeof useTranslations>;
  tags: string[];
  video: boolean;
  viewerImageIndex: number;
};
