package services

import (
	"maps"

	"yuem-go/backend-gin/internal/localization"
)

var DefaultSettings = defaultSettings()

func defaultSettings() map[string]any {
	settings := map[string]any{
		"ai_username_review_enabled":                        false,
		"ai_content_review_enabled":                         false,
		SiteTitleSetting:                                    localizedSettingDefault(DefaultSiteTitle),
		SiteDescriptionSetting:                              localizedSettingDefault(DefaultSiteDescription),
		SiteAvatarURLSetting:                                "",
		"post_content_max_length":                           100000,
		"post_resource_section_position":                    "before_content",
		"guest_access_restricted":                           false,
		"guest_access_note_restricted":                      false,
		"guest_access_video_restricted":                     false,
		"guest_access_admin_restricted":                     true,
		"onboarding_interest_options":                       defaultOnboardingInterestOptions(),
		"onboarding_custom_fields":                          "[]",
		"onboarding_enabled":                                true,
		"onboarding_allow_skip":                             true,
		"onboarding_avatar_enabled":                         true,
		"onboarding_avatar_required":                        true,
		"onboarding_background_enabled":                     true,
		"onboarding_background_required":                    true,
		"onboarding_name_enabled":                           true,
		"onboarding_name_required":                          true,
		"onboarding_signature_enabled":                      true,
		"onboarding_signature_required":                     false,
		"onboarding_interests_enabled":                      false,
		"onboarding_interests_required":                     false,
		"onboarding_min_interests":                          1,
		"onboarding_points_intro_title":                     localizedSettingDefault("What are points?"),
		"onboarding_points_intro_summary":                   localizedSettingDefault("Points can be used to redeem gift cards, participate in creator growth rewards, and track your active contributions in the community."),
		"onboarding_points_intro_detail":                    localizedSettingDefault("You may earn points by completing your profile, publishing content, interacting, and browsing. Points can be viewed in detail and exchanged for gift cards at the Points Center."),
		"onboarding_result_title":                           localizedSettingDefault("Initial setup complete"),
		"onboarding_result_saved_text":                      localizedSettingDefault("Profile saved."),
		"onboarding_points_wallet_label":                    localizedSettingDefault("Open Points Center"),
		"onboarding_points_wallet_url":                      "/wallet",
		"video_center_enabled":                              true,
		"video_center_homepage_enabled":                     false,
		"video_center_recommend_limit":                      4,
		"video_center_account_cutoff":                       "2026-06-12T00:00:00Z",
		OAuth2AppCallbackURLsSetting:                        "xsewebfast://auth-return",
		"app_download_android_enabled":                      true,
		"app_download_android_name":                         "Yuem Android",
		"app_download_android_version_name":                 "",
		"app_download_android_version_code":                 0,
		"app_download_android_download_url":                 "",
		"app_download_android_size_label":                   "",
		"app_download_android_size_bytes":                   0,
		"app_download_android_package_name":                 "",
		"app_download_android_release_notes":                "",
		"app_download_android_fast_enabled":                 true,
		"app_download_android_fast_name":                    "Yuem Android 极速版",
		"app_download_android_fast_version_name":            "",
		"app_download_android_fast_version_code":            0,
		"app_download_android_fast_download_url":            "",
		"app_download_android_fast_size_label":              "≤ 1 MB",
		"app_download_android_fast_size_bytes":              1048576,
		"app_download_android_fast_package_name":            "com.yuelk.xsewebfast",
		"app_download_android_fast_release_notes":           "",
		"app_download_ios_enabled":                          true,
		"app_download_ios_name":                             "Yuem iOS",
		"app_download_ios_version_name":                     "",
		"app_download_ios_version_code":                     0,
		"app_download_ios_download_url":                     "",
		"app_download_ios_size_label":                       "",
		"app_download_ios_size_bytes":                       0,
		"app_download_ios_bundle_id":                        "",
		"app_download_ios_release_notes":                    "",
		"ua_block_enabled":                                  false,
		"ua_block_devices":                                  "[]",
		"ua_block_page_html":                                "",
		"ua_block_redirect_url":                             "",
		"maintenance_enabled":                               false,
		"maintenance_entry_code":                            "",
		"maintenance_auto_login_uid":                        0,
		"maintenance_started_at":                            "",
		"maintenance_estimated_end_at":                      "",
		"maintenance_message":                               localizedSettingDefault(""),
		"maintenance_border_visible":                        true,
		"maintenance_border_color":                          "#dc2626",
		"maintenance_border_opacity":                        1,
		"maintenance_border_dismissible":                    false,
		"database_vacuum_enabled":                           false,
		"database_vacuum_tables":                            "[]",
		"database_vacuum_interval_hours":                    24,
		"database_vacuum_next_run_at":                       "",
		"database_vacuum_last_run_at":                       "",
		"database_vacuum_last_result":                       "",
		FileRecycleRetentionDaysKey:                         DefaultFileRecycleRetentionDays,
		FileRecycleCleanupIntervalHoursKey:                  DefaultFileRecycleCleanupIntervalHours,
		"redis_maintenance_enabled":                         true,
		"redis_maintenance_interval_minutes":                60,
		"redis_access_log_retention_hours":                  defaultRedisAccessLogRetentionHours,
		"redis_access_log_max_entries":                      defaultRedisAccessLogMaxEntries,
		"redis_system_log_retention_hours":                  168,
		"redis_system_log_max_entries":                      defaultRedisSystemLogMaxEntries,
		"redis_metrics_retention_hours":                     24,
		"redis_metrics_max_entries_per_key":                 defaultRedisMetricsMaxEntries,
		"redis_queue_event_retention_hours":                 24,
		"redis_queue_event_max_entries":                     defaultRedisQueueEventMaxEntries,
		"redis_completed_retention_hours":                   24,
		"redis_archived_retention_hours":                    720,
		"redis_archived_max_tasks_per_queue":                1000,
		"redis_memory_warning_percent":                      75,
		"redis_memory_critical_percent":                     90,
		"access_token_ttl_seconds":                          3600,
		"refresh_token_active_ttl_seconds":                  7776000,
		"refresh_token_renewal_interval_seconds":            86400,
		"refresh_token_mode":                                RefreshTokenModeRedisOpaque,
		"refresh_token_auto_renew_enabled":                  true,
		"session_inactive_ttl_seconds":                      604800,
		"redis_session_inactive_days":                       7,
		"redis_user_active_session_limit":                   5,
		"redis_maintenance_queue_overrides":                 `{"audit-log":{"completed_retention_hours":72,"archived_retention_hours":720,"archived_max_tasks":1000},"video-transcoding":{"completed_retention_hours":72,"archived_retention_hours":720,"archived_max_tasks":1000},"image-protection":{"completed_retention_hours":2,"archived_retention_hours":720,"archived_max_tasks":1000}}`,
		"redis_maintenance_next_run_at":                     "",
		"redis_maintenance_last_run_at":                     "",
		"redis_maintenance_last_result":                     "",
		"image_webp_enabled":                                true,
		"image_webp_quality":                                85,
		"image_avatar_webp_quality":                         75,
		"image_webp_method":                                 4,
		"image_webp_alpha_quality":                          100,
		"image_webp_lossless":                               false,
		"image_libvips_enabled":                             false,
		"image_max_width":                                   0,
		"image_max_height":                                  0,
		"image_processing_concurrency":                      1,
		"image_post_max_count":                              100,
		"image_archive_enabled":                             true,
		"image_archive_threshold":                           25,
		"image_protection_enabled":                          false,
		"image_protection_notice_enabled":                   true,
		"image_protection_max_dimension":                    2048,
		"image_protection_allowed_failure_percent":          20,
		"image_protection_output_mode":                      "lossless_webp",
		"image_protection_webp_quality":                     95,
		"image_select_all_enabled":                          true,
		"paid_content_balance_enabled":                      true,
		"paid_content_points_enabled":                       true,
		"paid_content_points_max_price":                     DefaultPaidContentPointsMaxPrice,
		"paid_content_balance_max_price":                    DefaultPaidContentBalanceMaxPrice,
		"hidden_watermark_enabled":                          true,
		"hidden_watermark_protected_only":                   true,
		"hidden_watermark_include_uid":                      true,
		"hidden_watermark_include_user_id":                  true,
		"hidden_watermark_include_username":                 false,
		"hidden_watermark_include_time":                     true,
		"hidden_watermark_include_file_hash":                true,
		"hidden_watermark_include_custom":                   false,
		"hidden_watermark_custom_text":                      "",
		"hidden_watermark_engine":                           "auto",
		"hidden_watermark_profile":                          "current",
		"hidden_watermark_block_width":                      8,
		"hidden_watermark_block_height":                     6,
		"hidden_watermark_coefficient_mode":                 "d1d2",
		"hidden_watermark_d1":                               21,
		"hidden_watermark_d2":                               9,
		"hidden_watermark_ecc_mode":                         "golay",
		"hidden_watermark_golay_seed":                       1234567890,
		"hidden_watermark_remote_password_wm":               1,
		"hidden_watermark_remote_password_img":              1,
		"hidden_watermark_remote_engine":                    "auto",
		"hidden_watermark_remote_profile":                   "adaptive",
		"hidden_watermark_remote_custom_d1":                 18,
		"hidden_watermark_remote_custom_d2":                 8,
		"hidden_watermark_remote_timeout_seconds":           50,
		"hidden_watermark_remote_operation_timeout_seconds": 45,
		"hidden_watermark_extract_all_users":                false,
		"hidden_watermark_extract_user_ids":                 "",
		"hidden_watermark_extract_usernames":                "",
		notificationSuppressionEnabledKey:                   true,
		notificationSuppressionWindowKey:                    DefaultNotificationInteractionSuppressionWindowSeconds,
		notificationSuppressionThresholdKey:                 DefaultNotificationInteractionSuppressionThreshold,
		"points_daily_cap":                                  50,
		"recommend_config":                                  `{"browse_weight":1,"history_weight":1,"click_weight":1,"like_weight":3,"collect_weight":4,"view_weight":1,"category_weight":2,"tag_weight":2.5,"title_weight":2,"content_weight":1.2,"following_weight":3,"mutual_follow_weight":4,"popularity_weight":1.5,"popularity_like_weight":1,"popularity_collect_weight":1.5,"popularity_comment_weight":2,"popularity_view_weight":0.5,"interest_weight":2,"freshness_weight":1,"time_decay_half_life":7,"behavior_decay_half_life":14,"content_type_boost_image":1.5,"content_type_boost_video":1.5,"content_type_boost_external":0.8,"candidate_pool_multiplier":5,"max_recommended":500,"max_hot":300,"fresh_pool_hours":48,"fresh_pool_size":50,"new_post_boost_max":1000,"new_post_boost_half_life":0.5,"admin_boost_weight":1,"suppressed_penalty":-2000,"pinned_boost":10000}`,
	}
	maps.Copy(settings, defaultAISettings())
	return settings
}

var LocalizedSettingKeys = map[string]bool{
	SiteTitleSetting:                  true,
	SiteDescriptionSetting:            true,
	"onboarding_interest_options":     true,
	"onboarding_points_intro_title":   true,
	"onboarding_points_intro_summary": true,
	"onboarding_points_intro_detail":  true,
	"onboarding_result_title":         true,
	"onboarding_result_saved_text":    true,
	"onboarding_points_wallet_label":  true,
	"maintenance_message":             true,
}

func localizedSettingDefault(value any) map[string]any {
	out := map[string]any{}
	for _, locale := range localization.Supported {
		out[locale] = value
	}
	return out
}

func defaultOnboardingInterestOptions() map[string]any {
	return localizedSettingDefault([]string{"Bondage", "Handcuffs", "Leg irons"})
}
