"use client";

import { AlertCircle, FileText, MessageSquare, ShieldCheck, Star, Users } from "lucide-react";
import type { ResourceConfig } from "./types";
import { booleanOptions, postTypeOptions, reportStatusOptions, reportTargetTypeOptions, statusOptions, verifiedOptions, visibilityOptions } from "./types";
import { VerificationImagesCell } from "./resource-editor";
import { IdentityCell, LongTextCell, PostCell, StatusPill } from "./resource-cells";
import { activeLabel, auditStatusLabel, auditTone, clampText, compactMetrics, fieldText, formatDateTime, formatMoney, reportStatusLabel, reportTone, reporterName, truthy, verificationTypeLabel, visibilityLabel } from "./helpers";

export const primaryResourceConfigs: ResourceConfig[] = [
  {
    resource: "users",
    label: "用户管理",
    singular: "用户",
    description: "账号、资料、认证与活跃状态",
    icon: Users,
    tone: "blue",
    columns: [
      { key: "user_id", label: "账号", render: (row) => <IdentityCell row={row} />, className: "w-[300px]" },
      { key: "uid", labelKey: "uid", render: (row) => <LongTextCell value={String(row.uid ?? row.id ?? "-")} muted lines={1} />, className: "w-[110px]" },
      { key: "oauth2_id", labelKey: "oauth2Id", render: (row) => <LongTextCell value={String(row.oauth2_id ?? "-")} muted lines={1} />, className: "w-[150px]" },
      { key: "points", labelKey: "points", render: (row) => <span className="font-semibold text-amber-700">{formatMoney(row.points)}</span>, className: "w-[120px]" },
      { key: "email", label: "邮箱", render: (row) => <LongTextCell value={row.email} muted />, className: "w-[260px]" },
      { key: "is_active", label: "状态", render: (row) => <StatusPill value={activeLabel(row.is_active)} tone={truthy(row.is_active) ? "green" : "slate"} /> },
      { key: "created_at", label: "注册时间", render: (row) => formatDateTime(row.created_at) },
    ],
    filters: [
      { key: "is_active", label: "状态", type: "boolean", options: booleanOptions },
      { key: "location", label: "地区" },
    ],
    fields: [
      { key: "user_id", label: "账号", required: true },
      { key: "nickname", label: "昵称", required: true },
      { key: "email", label: "邮箱" },
      { key: "password", label: "密码", type: "password", placeholder: "编辑时留空则不修改" },
      { key: "avatar", label: "头像", upload: "image" },
      { key: "background", label: "主页背景", upload: "image" },
      { key: "bio", label: "简介", type: "textarea" },
      { key: "location", label: "地区" },
      { key: "is_active", label: "启用", type: "boolean" },
      { key: "verified", label: "认证等级", type: "select", options: verifiedOptions, optionValueType: "number" },
    ],
    defaultSort: "created_at",
    tableMinWidth: 1440,
  },
  {
    resource: "posts",
    label: "内容管理",
    singular: "内容",
    description: "笔记、视频、草稿、可见性与原创激励",
    icon: FileText,
    tone: "blue",
    columns: [
      { key: "title", label: "内容", render: (row) => <PostCell row={row} /> },
      { key: "nickname", label: "作者", render: (row) => fieldText(row, "nickname") },
      { key: "visibility", label: "可见性", render: (row) => <StatusPill value={visibilityLabel(row.visibility)} tone={row.visibility === "public" ? "green" : "slate"} /> },
      { key: "public_access_exempt", label: "公开豁免", render: (row) => <StatusPill value={truthy(row.public_access_exempt) ? "开放" : "常规"} tone={truthy(row.public_access_exempt) ? "green" : "slate"} /> },
      { key: "like_count", label: "互动", render: (row) => compactMetrics(row, ["view_count", "like_count", "comment_count"]) },
      { key: "created_at", label: "发布时间", render: (row) => formatDateTime(row.created_at) },
    ],
    filters: [
      { key: "type", label: "类型", type: "select", options: postTypeOptions },
      { key: "visibility", label: "可见性", type: "select", options: visibilityOptions },
      { key: "is_draft", label: "草稿", type: "boolean", options: booleanOptions },
      { key: "public_access_exempt", label: "公开豁免", type: "boolean", options: booleanOptions },
    ],
    fields: [
      { key: "user_id", label: "作者", type: "number", required: true, picker: "users", pickerPlaceholder: "搜索昵称、账号或邮箱" },
      { key: "title", label: "标题", required: true },
      { key: "content", label: "正文", type: "textarea" },
      { key: "category_id", label: "分类", type: "number", picker: "categories", pickerPlaceholder: "搜索分类名称" },
      { key: "type", label: "类型", type: "select", options: postTypeOptions },
      { key: "visibility", label: "可见性", type: "select", options: visibilityOptions },
      { key: "is_draft", label: "草稿", type: "boolean" },
      { key: "public_access_exempt", label: "公开访问豁免", type: "boolean" },
      { key: "image_urls", label: "图片", upload: "image", uploadTarget: "json-list", placeholder: "上传图片后自动追加" },
      { key: "video_url", label: "视频 URL", upload: "video" },
      { key: "cover_url", label: "视频封面", upload: "image" },
    ],
    defaultSort: "created_at",
  },
  {
    resource: "content-review",
    label: "内容审核",
    singular: "审核项",
    description: "自动审核、人工复核、重试与处置",
    icon: ShieldCheck,
    tone: "amber",
    columns: [
      { key: "content", label: "内容", render: (row) => clampText(fieldText(row, "content")) },
      { key: "nickname", label: "用户", render: (row) => fieldText(row, "nickname") },
      { key: "risk_level", label: "风险", render: (row) => <StatusPill value={fieldText(row, "risk_level")} tone="amber" /> },
      { key: "status", label: "状态", render: (row) => <StatusPill value={auditStatusLabel(row.status)} tone={auditTone(row.status)} /> },
      { key: "created_at", label: "提交时间", render: (row) => formatDateTime(row.created_at) },
    ],
    filters: [
      { key: "status", label: "状态", type: "select", options: statusOptions },
      { key: "type", label: "类型", type: "select", options: [{ value: "3", label: "内容" }, { value: "4", label: "评论" }] },
    ],
    fields: [
      { key: "status", label: "状态", type: "select", options: statusOptions },
      { key: "reason", label: "原因", type: "richtext" },
      { key: "risk_level", label: "风险等级", type: "select", options: [
        { value: "low", label: "低风险" },
        { value: "medium", label: "中风险" },
        { value: "high", label: "高风险" },
      ] },
    ],
    defaultSort: "created_at",
  },
  {
    resource: "reports",
    label: "举报处理",
    singular: "举报",
    description: "用户举报、处理状态与管理员备注",
    icon: AlertCircle,
    tone: "red",
    columns: [
      { key: "reason", label: "原因", render: (row) => clampText(fieldText(row, "reason")) },
      { key: "target_type", label: "对象", render: (row) => fieldText(row, "target_type") },
      { key: "reporter", label: "举报人", render: (row) => reporterName(row) },
      { key: "status", label: "状态", render: (row) => <StatusPill value={reportStatusLabel(row.status)} tone={reportTone(row.status)} /> },
      { key: "created_at", label: "举报时间", render: (row) => formatDateTime(row.created_at) },
    ],
    filters: [
      { key: "status", label: "状态", type: "select", options: reportStatusOptions },
      { key: "target_type", label: "对象", type: "select", options: reportTargetTypeOptions },
    ],
    fields: [
      { key: "status", label: "状态", type: "select", options: reportStatusOptions },
      { key: "admin_note", label: "处理备注", type: "textarea" },
      { key: "description", label: "描述", type: "textarea" },
    ],
    defaultSort: "created_at",
    canCreate: false,
    canBulkDelete: false,
  },
  {
    resource: "audit",
    label: "认证审核",
    singular: "认证申请",
    description: "认证类审核申请",
    icon: Star,
    tone: "purple",
    columns: [
      { key: "content", label: "认证详情", render: (row) => clampText(fieldText(row, "content")) },
      { key: "nickname", label: "用户", render: (row) => fieldText(row, "nickname") },
      { key: "type", label: "类型", render: (row) => <StatusPill value={verificationTypeLabel(row.type)} tone={String(row.type) === "2" ? "purple" : "blue"} /> },
      { key: "audit_result", label: "图片", render: (row) => <VerificationImagesCell row={row} /> },
      { key: "status", label: "状态", render: (row) => <StatusPill value={auditStatusLabel(row.status)} tone={auditTone(row.status)} /> },
      { key: "created_at", label: "提交时间", render: (row) => formatDateTime(row.created_at) },
    ],
    filters: [{ key: "status", label: "状态", type: "select", options: statusOptions }],
    fields: [{ key: "status", label: "状态", type: "select", options: statusOptions }, { key: "reason", label: "原因", type: "richtext" }],
  },
  {
    resource: "comments",
    label: "评论管理",
    singular: "评论",
    description: "评论内容、审核状态与公开状态",
    icon: MessageSquare,
    tone: "green",
    columns: [
      { key: "content", label: "评论", render: (row) => clampText(fieldText(row, "content")) },
      { key: "nickname", label: "用户", render: (row) => fieldText(row, "nickname") },
      { key: "post_title", label: "所属内容", render: (row) => clampText(fieldText(row, "post_title")) },
      { key: "audit_status", label: "审核", render: (row) => auditStatusLabel(row.audit_status) },
      { key: "created_at", label: "时间", render: (row) => formatDateTime(row.created_at) },
    ],
    filters: [{ key: "audit_status", label: "审核", type: "select", options: statusOptions }],
    fields: [
      { key: "content", label: "评论", type: "textarea" },
      { key: "audit_status", label: "审核状态", type: "select", options: statusOptions },
      { key: "is_public", label: "公开", type: "boolean" },
      { key: "like_count", label: "点赞数", type: "number" },
    ],
  },
  {
    resource: "ai-moderation-logs",
    label: "AI 审核日志",
    singular: "AI 审核日志",
    description: "评论与发帖 AI 审核结果、触发原因、违规次数和处置动作",
    icon: ShieldCheck,
    tone: "amber",
    columns: [
      { key: "target_type", label: "目标", render: (row) => <StatusPill value={fieldText(row, "target_type")} tone="amber" /> },
      { key: "target_id", label: "目标 ID", render: (row) => fieldText(row, "target_id") },
      { key: "nickname", label: "用户", render: (row) => fieldText(row, "nickname") },
      { key: "content_snapshot", label: "审核内容", render: (row) => clampText(fieldText(row, "content_snapshot")) },
      { key: "trigger_reason", label: "触发原因", render: (row) => clampText(fieldText(row, "trigger_reason")) },
      { key: "categories", label: "命中规则", render: (row) => clampText(fieldText(row, "categories")) },
      { key: "action", label: "处置", render: (row) => <StatusPill value={fieldText(row, "action")} tone={String(row.action) === "observe" ? "slate" : "red"} /> },
      { key: "status", label: "状态", render: (row) => <StatusPill value={fieldText(row, "status")} tone={String(row.status) === "approved" ? "green" : "amber"} /> },
      { key: "user_violation_count", label: "违规次数", render: (row) => fieldText(row, "user_violation_count") },
      { key: "created_at", label: "时间", render: (row) => formatDateTime(row.created_at) },
    ],
    filters: [
      { key: "target_type", label: "目标", type: "select", options: [{ value: "comment", label: "评论" }, { value: "post", label: "帖子" }] },
      { key: "status", label: "状态" },
      { key: "action", label: "处置", type: "select", options: [{ value: "observe", label: "观察" }, { value: "delete", label: "删除" }, { value: "private", label: "私密" }] },
    ],
    fields: [
      { key: "trigger_reason", label: "触发原因", type: "textarea" },
      { key: "content_snapshot", label: "审核内容", type: "textarea" },
      { key: "categories", label: "命中规则 JSON", type: "json" },
      { key: "model_result", label: "模型 JSON", type: "json" },
      { key: "metadata", label: "审核上下文 JSON", type: "json" },
      { key: "error_message", label: "错误详情", type: "textarea" },
    ],
    defaultSort: "created_at",
    readOnly: true,
    canCreate: false,
    canEdit: false,
    canDelete: false,
    canBulkDelete: false,
    tableMinWidth: 1320,
  },
];
