"use client";

import { Folder, Heart, KeyRound, Package, Users } from "lucide-react";
import type { ResourceConfig } from "./types";
import { appPlatformOptions, booleanOptions, likeTargetTypeOptions } from "./types";
import { fieldBytes, simpleColumns } from "./helpers";

export const engagementResourceConfigs: ResourceConfig[] = [
  {
    resource: "collections",
    label: "收藏记录",
    singular: "收藏",
    description: "用户收藏内容记录",
    icon: Folder,
    tone: "blue",
    columns: simpleColumns(["user_display_id", "nickname", "post_title", "created_at"]),
    filters: [{ key: "user_display_id", label: "用户" }, { key: "post_id", label: "内容", type: "text" }],
    fields: [{ key: "user_id", label: "用户", type: "number", picker: "users", pickerPlaceholder: "搜索昵称、账号或邮箱" }, { key: "post_id", label: "内容", type: "number", picker: "posts", pickerPlaceholder: "搜索标题、正文或作者" }],
    canCreate: false,
    canEdit: false,
    canDelete: true,
    canBulkDelete: false,
  },
  {
    resource: "follows",
    label: "关注关系",
    singular: "关注",
    description: "关注与粉丝关系",
    icon: Users,
    tone: "green",
    columns: simpleColumns(["follower_display_id", "follower_nickname", "following_display_id", "following_nickname", "created_at"]),
    filters: [{ key: "follower_display_id", label: "关注者" }, { key: "following_display_id", label: "被关注者" }],
    fields: [{ key: "follower_id", label: "关注者", type: "number", picker: "users", pickerPlaceholder: "搜索关注者" }, { key: "following_id", label: "被关注者", type: "number", picker: "users", pickerPlaceholder: "搜索被关注者" }],
    canCreate: false,
    canEdit: false,
    canDelete: true,
    canBulkDelete: false,
  },
  {
    resource: "likes",
    label: "点赞记录",
    singular: "点赞",
    description: "点赞对象与用户",
    icon: Heart,
    tone: "slate",
    columns: simpleColumns(["user_display_id", "nickname", "target_type", "target_id", "created_at"]),
    filters: [{ key: "user_display_id", label: "用户" }, { key: "target_type", label: "对象类型", type: "select", options: likeTargetTypeOptions }],
    fields: [{ key: "user_id", label: "用户", type: "number", picker: "users", pickerPlaceholder: "搜索昵称、账号或邮箱" }, { key: "target_type", label: "对象类型", type: "select", options: likeTargetTypeOptions, optionValueType: "number" }, { key: "target_id", label: "对象编号", type: "number" }],
    canCreate: false,
    canEdit: false,
    canDelete: true,
    canBulkDelete: false,
  },
  {
    resource: "licenses",
    label: "授权码",
    singular: "授权码",
    description: "设备授权、机器信息与有效期",
    icon: KeyRound,
    tone: "purple",
    columns: simpleColumns(["license_key", "machine_model", "machine_id", "is_active", "expires_at"]),
    filters: [{ key: "is_active", label: "启用", type: "boolean", options: booleanOptions }],
    fields: [
      { key: "license_key", label: "授权码", required: true },
      { key: "machine_model", label: "机器型号" },
      { key: "machine_id", label: "机器码" },
      { key: "is_active", label: "启用", type: "boolean" },
      { key: "expires_at", label: "过期时间", type: "datetime" },
      { key: "remark", label: "备注", type: "textarea" },
    ],
  },
  {
    resource: "app-versions",
    label: "App 版本",
    singular: "App 版本",
    description: "移动端版本、更新日志与安装包",
    icon: Package,
    tone: "blue",
    columns: [
      ...simpleColumns(["app_name", "platform", "version_name", "version_code"]),
      { key: "size_bytes", label: "安装包大小", render: (row) => fieldBytes(row, "size_bytes") },
      ...simpleColumns(["force_update", "is_active"]),
    ],
    filters: [{ key: "platform", label: "平台", type: "select", options: appPlatformOptions }, { key: "is_active", label: "启用", type: "boolean", options: booleanOptions }],
    fields: [
      { key: "app_name", label: "应用名称", required: true },
      { key: "version_code", label: "版本号", type: "number", required: true },
      { key: "version_name", label: "版本名", required: true },
      { key: "platform", label: "平台", type: "select", options: appPlatformOptions, required: true },
      { key: "download_url", label: "下载地址", required: true, upload: "apk" },
      { key: "size_mb", label: "安装包大小（MB）", type: "number", defaultValue: 0 },
      { key: "update_log", label: "更新日志", type: "textarea" },
      { key: "force_update", label: "强制更新", type: "boolean", defaultValue: false },
      { key: "is_active", label: "启用", type: "boolean", defaultValue: true },
    ],
  },
];
