package config

import (
	"path/filepath"
	"strings"
	"time"
)

func Load() Config {
	LoadEnvFiles()
	databaseURL := databaseURLFromEnv()
	uploadRoot := getEnv("UPLOAD_ROOT", getEnv("LOCAL_UPLOAD_DIR", "uploads"))
	uploadTempRoot := getEnv("UPLOAD_TEMP_DIR", getEnv("VIDEO_CHUNK_TEMP_DIR", "uploads/tmp"))
	return Config{
		Server: ServerConfig{
			Port:              getEnv("GIN_PORT", getEnv("PORT", "3001")),
			Env:               getEnv("APP_ENV", getEnv("GIN_MODE", "development")),
			ClientIPHeaders:   splitCSV(getEnv("CLIENT_IP_HEADERS", "X-Forwarded-For,X-Real-IP,CF-Connecting-IP")),
			RequestLogLevel:   getEnv("REQUEST_LOG_LEVEL", getEnv("LOG_LEVEL", "info")),
			RequestLogSilence: splitCSV(getEnv("REQUEST_LOG_SILENCE", "/api/im/ws,/api/maintenance/status")),
		},
		Log: LogConfig{
			Level:             getEnv("LOG_LEVEL", "info"),
			FileEnabled:       boolEnv("LOG_FILE_ENABLED", true),
			FileDir:           getEnv("LOG_FILE_DIR", "logs"),
			FileRetentionDays: intEnv("LOG_FILE_RETENTION_DAYS", 7),
		},
		GeoIP: GeoIPConfig{
			CountryMMDBPath: getEnv("GEOIP_COUNTRY_MMDB_PATH", "data/geoip/Country.mmdb"),
			CountryMMDBURL:  getEnv("GEOIP_COUNTRY_MMDB_URL", "https://github.com/Loyalsoldier/geoip/releases/latest/download/Country.mmdb"),
			SHA256URL:       getEnv("GEOIP_COUNTRY_MMDB_SHA256_URL", "https://github.com/Loyalsoldier/geoip/releases/latest/download/Country.mmdb.sha256sum"),
		},
		AccessBlock: AccessBlockConfig{
			Disabled:                boolEnv("ACCESS_BLOCK_DISABLED", false),
			VersionPollInterval:     durationEnv("ACCESS_BLOCK_VERSION_POLL_INTERVAL", 5*time.Second),
			ImportDisabled:          boolEnv("ACCESS_BLOCK_IMPORT_DISABLED", false),
			ImportMinInterval:       time.Duration(intEnv("ACCESS_BLOCK_IMPORT_MIN_INTERVAL_SECONDS", 300)) * time.Second,
			ImportHTTPTimeout:       time.Duration(intEnv("ACCESS_BLOCK_IMPORT_HTTP_TIMEOUT_SECONDS", 10)) * time.Second,
			ImportMaxBytes:          int64Env("ACCESS_BLOCK_IMPORT_MAX_BYTES", 2*1024*1024),
			ImportSchedulerInterval: time.Duration(intEnv("ACCESS_BLOCK_IMPORT_SCHEDULER_INTERVAL_SECONDS", 60)) * time.Second,
			ImportDefaultInterval:   time.Duration(intEnv("ACCESS_BLOCK_IMPORT_DEFAULT_INTERVAL_SECONDS", 3600)) * time.Second,
		},
		CORS: CORSConfig{
			Origins: splitCSV(getEnv("CORS_ORIGINS", getEnv("CORS_ORIGIN", "http://localhost:5173,http://localhost:3001,https://xse.yuelk.com,capacitor://localhost,ionic://localhost"))),
		},
		Database: DatabaseConfig{
			URL:                    databaseURL,
			Driver:                 databaseDriver(databaseURL),
			Host:                   getEnv("DB_HOST", ""),
			User:                   getEnv("DB_USER", ""),
			Password:               getEnv("DB_PASSWORD", ""),
			Name:                   getEnv("DB_NAME", ""),
			Port:                   intEnv("DB_PORT", 0),
			PoolSize:               intEnv("DB_POOL_SIZE", 10),
			MaxIdleConns:           intEnv("DB_MAX_IDLE_CONNS", 0),
			ConnMaxLifetimeMS:      intEnv("DB_CONN_MAX_LIFETIME_MS", 0),
			ConnectionTimeoutMS:    intEnv("DB_CONNECTION_TIMEOUT", 10000),
			IdleTimeoutMS:          intEnv("DB_IDLE_TIMEOUT", 60000),
			Charset:                getEnv("DB_CHARSET", "utf8mb4"),
			Timezone:               getEnv("DB_TIMEZONE", "+08:00"),
			Schema:                 getEnv("DB_SCHEMA", "public"),
			SSLMode:                getEnv("DB_SSL_MODE", "disable"),
			StatementTimeoutMS:     intEnv("DB_STATEMENT_TIMEOUT", 0),
			LockTimeoutMS:          intEnv("DB_LOCK_TIMEOUT", 0),
			LogLevel:               getEnv("DB_LOG_LEVEL", getEnv("LOG_LEVEL", "warn")),
			IgnoreRecordNotFound:   boolEnv("DB_IGNORE_RECORD_NOT_FOUND_ERROR", true),
			PrepareStmt:            boolEnv("DB_PREPARE_STMT", false),
			CreateBatchSize:        intEnv("DB_CREATE_BATCH_SIZE", 0),
			SkipDefaultTransaction: boolEnv("DB_SKIP_DEFAULT_TRANSACTION", false),
			AutoMigrate:            boolEnv("DB_AUTO_MIGRATE", true),
		},
		Redis: RedisConfig{
			Addr:                getEnv("REDIS_ADDR", getEnv("REDIS_HOST", "localhost")+":"+getEnv("REDIS_PORT", "6379")),
			Password:            getEnv("REDIS_PASSWORD", ""),
			DB:                  intEnv("REDIS_DB", 0),
			PoolSize:            intEnv("REDIS_POOL_SIZE", 0),
			MinIdleConns:        intEnv("REDIS_MIN_IDLE_CONNS", 0),
			CacheEnabled:        boolEnv("REDIS_CACHE_ENABLED", true),
			CacheCommandTimeout: time.Duration(intEnv("REDIS_CACHE_COMMAND_TIMEOUT_MS", 50)) * time.Millisecond,
			CacheDefaultTTL:     time.Duration(intEnv("REDIS_CACHE_DEFAULT_TTL_SECONDS", 30)) * time.Second,
			CacheL1TTL:          time.Duration(intEnv("REDIS_CACHE_L1_TTL_SECONDS", 2)) * time.Second,
			CacheL1MaxEntries:   intEnv("REDIS_CACHE_L1_MAX_ENTRIES", 0),
		},
		Auth: AuthConfig{
			JWTSecret:             getEnv("JWT_SECRET", "xiaoshiliu_secret_key_2025"),
			JWTExpiresIn:          getEnv("JWT_EXPIRES_IN", "3600"),
			AdminJWTExpiresIn:     getEnv("ADMIN_JWT_EXPIRES_IN", getEnv("JWT_EXPIRES_IN", "3600")),
			RefreshTokenExpiresIn: getEnv("REFRESH_TOKEN_EXPIRES_IN", "7776000"),
		},
		Debug: DebugConfig{
			SwaggerDocsPath:  getEnv("SWAGGER_DOCS_PATH", "swagger-MYQD6LuH0heYgcK5DT10Al00dj6OW8Wc"),
			JWTTestTokenPath: getEnv("JWT_TEST_TOKEN_PATH", "jwt-MYQD6LuH0heYgcK5DT10Al00dj6OW8Wc"),
		},
		API: APIConfig{
			BaseURL: strings.TrimRight(getEnv("API_BASE_URL", "http://localhost:3001"), "/"),
			Timeout: time.Duration(intEnv("API_TIMEOUT", 30000)) * time.Millisecond,
		},
		PyVideo: PyVideoConfig{
			APIKey:            getEnv("PYVIDEO_API_KEY", ""),
			VideoCenterAPIKey: getEnv("VIDEO_CENTER_API_KEY", getEnv("PYVIDEO_API_KEY", "")),
			UpstreamURL:       strings.TrimRight(getEnv("PYVIDEO_UPSTREAM_URL", "https://v.yuelk.com"), "/"),
		},
		Frontend: FrontendConfig{
			BaseURL: frontendBaseURL(),
		},
		Email: EmailConfig{
			Enabled: boolEnv("EMAIL_ENABLED", false),
			SMTP: SMTPConfig{
				Host:     getEnv("SMTP_HOST", "smtp.qq.com"),
				Port:     intEnv("SMTP_PORT", 465),
				Secure:   boolEnv("SMTP_SECURE", true),
				Username: getEnv("SMTP_USER", ""),
				Password: getEnv("SMTP_PASSWORD", ""),
			},
			FromName: getEnv("EMAIL_FROM_NAME", "Yuem Community"),
			FromMail: getEnv("EMAIL_FROM", ""),
		},
		OAuth2: OAuth2Config{
			Enabled:         boolEnv("OAUTH2_ENABLED", false),
			OnlyOAuth2:      boolEnv("OAUTH2_ONLY_LOGIN", false),
			LoginURL:        strings.TrimRight(getEnv("OAUTH2_LOGIN_URL", getEnv("OAUTH2_BASE_URL", "https://user.yuelk.com")), "/"),
			ClientID:        getEnv("OAUTH2_CLIENT_ID", ""),
			ClientSecret:    getEnv("OAUTH2_CLIENT_SECRET", ""),
			RedirectURI:     getEnv("OAUTH2_REDIRECT_URI", ""),
			RedirectBaseURL: strings.TrimRight(getEnv("OAUTH2_REDIRECT_BASE_URL", "http://localhost:3000"), "/"),
			CallbackPath:    getEnv("OAUTH2_CALLBACK_PATH", "/api/auth/oauth2/callback"),
			AppCallbackURL:  getEnv("OAUTH2_APP_CALLBACK_URL", "xsewebfast://auth-return"),
			EnableDPoP:      boolEnv("OAUTH2_DPOP_ENABLED", false),
		},
		Geetest: GeetestConfig{
			Enabled:    boolEnv("GEETEST_ENABLED", false),
			CaptchaID:  getEnv("GEETEST_CAPTCHA_ID", ""),
			CaptchaKey: getEnv("GEETEST_CAPTCHA_KEY", ""),
			APIServer:  strings.TrimRight(getEnv("GEETEST_API_SERVER", "https://gcaptcha4.geetest.com"), "/"),
		},
		IM: IMConfig{
			BaseURL:    strings.TrimRight(getEnv("IM_BASE", "https://ws-im.yuelk.com:29443"), "/"),
			HMACSecret: getEnv("IM_HMAC_SECRET", ""),
			MessageKey: getEnv("IM_MESSAGE_KEY", ""),
			Mode:       getEnv("IM_MODE", "direct"),
		},
		Chat: ChatWSConfig{
			Enabled:          boolEnv("CHAT_WS_ENABLED", false),
			BaseURL:          strings.TrimRight(getEnv("CHAT_WS_BASE_URL", "https://ws-im.yuelk.com:29443"), "/"),
			ProvisionSecret:  getEnv("CHAT_WS_PROVISION_SECRET", ""),
			EncryptionKey:    getEnv("CHAT_WS_ENCRYPTION_KEY", ""),
			TicketTTL:        time.Duration(intEnv("CHAT_WS_TICKET_TTL", 60)) * time.Second,
			HTTPTimeout:      time.Duration(intEnv("CHAT_WS_HTTP_TIMEOUT", 10000)) * time.Millisecond,
			MessageMaxLength: intEnv("CHAT_MESSAGE_MAX_LENGTH", 2000),
		},
		Balance: BalanceCenterConfig{
			APIURL:          strings.TrimRight(getEnv("BALANCE_API_URL", "https://user.yuelk.com"), "/"),
			APIKey:          getEnv("BALANCE_API_KEY", ""),
			Timeout:         durationEnv("BALANCE_API_TIMEOUT", 10*time.Second),
			ExchangeRateIn:  floatEnv("BALANCE_EXCHANGE_RATE_IN", 1.0),
			ExchangeRateOut: floatEnv("BALANCE_EXCHANGE_RATE_OUT", 1.0),
		},
		Creator: CreatorCenterConfig{
			PlatformFeeRate:         floatEnv("CREATOR_PLATFORM_FEE_RATE", 0),
			WithdrawEnabled:         boolEnv("CREATOR_WITHDRAW_ENABLED", false),
			MinWithdrawAmount:       floatEnv("CREATOR_MIN_WITHDRAW_AMOUNT", 10),
			ExtendedEarningsEnabled: boolEnv("CREATOR_EXTENDED_EARNINGS_ENABLED", false),
			EarningsRates: CreatorEarningsRates{
				PerView:     floatEnv("CREATOR_EARNINGS_PER_VIEW", 0.01),
				PerLike:     floatEnv("CREATOR_EARNINGS_PER_LIKE", 0.05),
				PerCollect:  floatEnv("CREATOR_EARNINGS_PER_COLLECT", 0.10),
				PerComment:  floatEnv("CREATOR_EARNINGS_PER_COMMENT", 0.02),
				PerFollower: floatEnv("CREATOR_EARNINGS_PER_FOLLOWER", 0.20),
			},
			DailyExtendedCap: floatEnv("CREATOR_DAILY_EXTENDED_EARNINGS_CAP", 0),
		},
		Upload: UploadConfig{
			RootDir:                   uploadRoot,
			LocalBase:                 strings.TrimRight(getEnv("LOCAL_BASE_URL", "http://localhost:3001"), "/"),
			MaxSize:                   parseSizeBytes(getEnv("UPLOAD_MAX_SIZE", "50mb"), 50*1024*1024),
			DeletePostUploadsOnDelete: boolEnv("DELETE_POST_UPLOADS_ON_DELETE", false),
			AvatarDir:                 getEnv("AVATAR_UPLOAD_DIR", "uploads/avatar"),
			BannerDir:                 getEnv("BANNER_UPLOAD_DIR", "uploads/banner"),
			Temp: UploadTempConfig{
				RootDir:                   uploadTempRoot,
				CleanupInterval:           durationEnv("UPLOAD_TEMP_CLEANUP_INTERVAL", 15*time.Minute),
				Retention:                 durationEnv("UPLOAD_TEMP_RETENTION", 24*time.Hour),
				ProtectedPackageRetention: durationEnv("PROTECTED_PACKAGE_RETENTION", 2*time.Hour),
			},
			Recycle: UploadRecycleConfig{
				Enabled:         boolEnv("UPLOAD_RECYCLE_ENABLED", true),
				RootDir:         getEnv("UPLOAD_RECYCLE_ROOT", filepath.Join(uploadRoot, ".trash")),
				Retention:       durationEnv("UPLOAD_RECYCLE_RETENTION", 30*24*time.Hour),
				CleanupInterval: durationEnv("UPLOAD_RECYCLE_CLEANUP_INTERVAL", 24*time.Hour),
			},
			FileSigning: UploadFileSigningConfig{
				Secret: getEnv("FILE_SIGNING_SECRET", getEnv("JWT_SECRET", "xiaoshiliu_secret_key_2025")),
				TTL:    time.Duration(intEnv("FILE_SIGNING_TTL_SECONDS", 15*60)) * time.Second,
			},
			Image: UploadImageConfig{
				Strategy:                getEnv("IMAGE_UPLOAD_STRATEGY", "imagehost"),
				LocalUploadDir:          getEnv("IMAGE_LOCAL_UPLOAD_DIR", "uploads/images"),
				ImageHostAPIURL:         getEnv("IMAGEHOST_API_URL", "https://api.xinyew.cn/api/jdtc"),
				ImageHostTimeoutSeconds: millisecondsEnvAsSeconds("IMAGEHOST_TIMEOUT", 60000),
				MaxSizeBytes:            parseSizeBytes(getEnv("IMAGE_MAX_SIZE", "10mb"), 10*1024*1024),
				R2:                      loadR2Config(),
			},
			Video: UploadVideoConfig{
				Strategy:        getEnv("VIDEO_UPLOAD_STRATEGY", "local"),
				LocalUploadDir:  getEnv("VIDEO_LOCAL_UPLOAD_DIR", getEnv("VIDEO_UPLOAD_DIR", "uploads/videos")),
				LegacyUploadDir: getEnv("VIDEO_UPLOAD_DIR", ""),
				CoverDir:        getEnv("VIDEO_COVER_DIR", "uploads/covers"),
				MaxSizeBytes:    parseSizeBytes(getEnv("VIDEO_MAX_SIZE", "100mb"), 100*1024*1024),
				R2:              loadR2Config(),
				Chunk: UploadChunkConfig{
					TempDir:           filepath.Join(uploadTempRoot, "chunks"),
					ChunkSize:         int64Env("VIDEO_CHUNK_SIZE", 3*1024*1024),
					CleanupIntervalMS: int64Env("VIDEO_CHUNK_CLEANUP_INTERVAL", 30*60*1000),
					ExpireTimeMS:      int64Env("VIDEO_CHUNK_EXPIRE_TIME", 2*60*60*1000),
				},
			},
			Attachment: UploadAttachmentConfig{
				Strategy:       getEnv("ATTACHMENT_UPLOAD_STRATEGY", "local"),
				LocalUploadDir: getEnv("ATTACHMENT_LOCAL_UPLOAD_DIR", "uploads/attachments"),
				MaxSizeBytes:   parseSizeBytes(getEnv("ATTACHMENT_MAX_SIZE", "50mb"), 50*1024*1024),
				R2:             loadR2Config(),
			},
		},
		Queue: QueueConfig{
			Enabled: boolEnv("QUEUE_ENABLED", false),
			Concurrency: QueueConcurrencyConfig{
				IPLocation:       intEnv("QUEUE_IP_LOCATION_CONCURRENCY", 5),
				ContentAudit:     intEnv("QUEUE_CONTENT_AUDIT_CONCURRENCY", 3),
				GeneralTask:      intEnv("QUEUE_GENERAL_TASK_CONCURRENCY", 5),
				AITask:           intEnv("QUEUE_AI_TASK_CONCURRENCY", 2),
				VideoTranscoding: intEnv("QUEUE_VIDEO_TRANSCODING_CONCURRENCY", 1),
				BatchNoteCreate:  intEnv("QUEUE_BATCH_NOTE_CREATE_CONCURRENCY", 3),
				ImageProtection:  intEnv("QUEUE_IMAGE_PROTECTION_CONCURRENCY", 1),
				AuditLog:         intEnv("QUEUE_AUDIT_LOG_CONCURRENCY", 2),
			},
			Retry: QueueRetryConfig{
				Attempts:     intEnv("QUEUE_RETRY_ATTEMPTS", 3),
				BackoffDelay: time.Duration(intEnv("QUEUE_RETRY_DELAY", 1000)) * time.Millisecond,
			},
		},
		Notify: NotificationChannelsConfig{
			EmailEnabled:       boolEnv("NOTIFICATION_EMAIL_ENABLED", false),
			SystemEmailEnabled: boolEnv("SYSTEM_NOTIFICATION_EMAIL_ENABLED", false),
			Discord: DiscordConfig{
				Enabled:    boolEnv("DISCORD_WEBHOOK_ENABLED", false),
				WebhookURL: getEnv("DISCORD_WEBHOOK_URL", ""),
				SiteName:   getEnv("DISCORD_SITE_NAME", "Yuem Community"),
				SiteURL:    getEnv("DISCORD_SITE_URL", "http://localhost:5173"),
			},
		},
		WebP:  loadWebPConfig(),
		Video: loadVideoTranscodingConfig(),
		Audit: ContentAuditConfig{
			Enabled: boolEnv("CONTENT_AUDIT_ENABLED", false),
			APIURL:  strings.TrimRight(getEnv("DIFY_API_URL", "http://aish.yuelk.com/v1/chat-messages"), "/"),
			APIKey:  getEnv("DIFY_API_KEY", ""),
		},
		Media: MediaConfig{
			AllowedDomains:      splitCSV(getEnv("ALLOWED_MEDIA_DOMAINS", "")),
			RecommendationDebug: boolEnv("RECOMMENDATION_DEBUG", false),
		},
		Verify: VerificationConfig{
			CollectSensitiveInfo: boolEnv("VERIFICATION_COLLECT_SENSITIVE_INFO", false),
		},
		Observe: ObservabilityConfig{
			SystemLogEnabled:      boolEnv("SYSTEM_LOG_ENABLED", true),
			SystemLogRetention:    time.Duration(intEnv("SYSTEM_LOG_RETENTION_HOURS", 168)) * time.Hour,
			MetricsEnabled:        boolEnv("PERFORMANCE_METRICS_ENABLED", true),
			MetricsRetention:      time.Duration(intEnv("PERFORMANCE_METRICS_RETENTION_HOURS", 24)) * time.Hour,
			MetricsBucket:         time.Duration(intEnv("PERFORMANCE_METRICS_BUCKET_SECONDS", 300)) * time.Second,
			RuntimeSampleInterval: time.Duration(intEnv("PERFORMANCE_SAMPLE_INTERVAL_SECONDS", 300)) * time.Second,
			SlowRequestThreshold:  time.Duration(intEnv("SLOW_REQUEST_THRESHOLD_MS", 1000)) * time.Millisecond,
			SlowQueryThreshold:    time.Duration(intEnv("SLOW_QUERY_THRESHOLD_MS", 500)) * time.Millisecond,
		},
		AccessLog: AccessLogConfig{
			Enabled:       boolEnv("ACCESS_LOG_ENABLED", true),
			Scope:         strings.ToLower(strings.TrimSpace(getEnv("ACCESS_LOG_SCOPE", "key"))),
			Behaviors:     splitCSV(getEnv("ACCESS_LOG_BEHAVIORS", "post_view,feed_view,search,post_create,draft_save,post_update,post_delete,draft_delete,comment_create,like,collect,follow,image_upload,video_upload,attachment_upload,apk_upload,upload,admin_access")),
			Retention:     time.Duration(intEnv("ACCESS_LOG_RETENTION_HOURS", 8760)) * time.Hour,
			BufferSize:    intEnv("ACCESS_LOG_BUFFER_SIZE", 4096),
			BatchSize:     intEnv("ACCESS_LOG_BATCH_SIZE", 100),
			FlushInterval: time.Duration(intEnv("ACCESS_LOG_FLUSH_INTERVAL_MS", 1000)) * time.Millisecond,
		},
		SecurityAuditLog: SecurityAuditLogConfig{
			Enabled:   boolEnv("SECURITY_AUDIT_LOG_ENABLED", true),
			Retention: time.Duration(intEnv("SECURITY_AUDIT_LOG_RETENTION_HOURS", 8760)) * time.Hour,
		},
	}
}
